export { Categories } from "./Categories";
export { CustomisationCTA } from "./CustomisationCTA";
export { FAQ } from "./FAQ";
export { FeaturedCollections } from "./FeaturedCollections";
export { FeaturedProducts } from "./FeaturedProducts";
export { Hero } from "./Hero";
export { LatestBlog } from "./LatestBlog";
export { ResourceCarousel } from "./ResourceCarousel";
export { TrustIndicators } from "./TrustIndicators";
